#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#include <substrate.h>
#import "LPView.h"
#import "LPViewController.h"
#import <liblockpages/LPPageController.h>
#import <Accelerate/Accelerate.h>
#import <UIKit/UIView.h>
#import <QuartzCore/QuartzCore.h>